### ISSUE TITLE
Can I smooth a path?

### ISSUE THREAD

**Issue by kasbah** [psychobolt/react-paperjs#10]
How would you go about applying the `smooth` function to a react-paperjs `Path` component?

http://paperjs.org/reference/path/#smooth

**Comment by psychobolt** [comment]
Currently, you may perform custom operations on mount or some event on the canvas e.g.

```jsx
   import { useEffect } from 'react';
   import { PaperContainer, Path } from '@psychobolt/react-paperjs';

   export default (pathProps, ...props) => {
      const pathRef = useRef(null);
      useEffect(() => pathRef.current && pathRef.current.smooth());
      return (
        <PaperContainer {...props}>
          <Path ref={pathRef} {...pathProps} />
        </PaperContainer>
      );
   }
```

**Comment by kasbah** [comment]
Ah, I see, thanks. Would it make sense to try and implement this in react-paperjs as a  prop `<Path smooth={...} />` by itself? I'd need to detect it and hook in to [here](https://github.com/psychobolt/react-paperjs/blob/4b368ea87f1f07558ac7c229ba24787f159518cc/src/Paper.types.js#L59-L63) somewhere? (Still a bit confused about how the lib works to be honest.)

**Comment by psychobolt** [comment]
Yes it would make sense. To make sure its applied after prop diffing you could add the logic [here](https://github.com/psychobolt/react-paperjs/blob/4b368ea87f1f07558ac7c229ba24787f159518cc/src/Paper.component.js#L41). Otherwise you will see a warning in [console](https://github.com/psychobolt/react-paperjs/blob/4b368ea87f1f07558ac7c229ba24787f159518cc/src/Paper.component.js#L54). ```instance does not have property smooth``` :poop:

updateProp is passed an ```type```, but currently not being used... so let's use it.
```sh
   // Paper.component.js
   import { CONSTANTS } from './Paper.types';
   // ...
   export function updateProps(instance, updatePayload, type) {
   // ...
     if (type === CONSTANTS.Path) {
       if (key === 'smoothProps') {
         instance.smooth(value);
       }
     }
  }
```
